#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/bem-team/bem-go-sdk,github.com/bem-team/bem-go-sdk-staging"

go build -o terraform-provider-bem
