#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/bem-team/bem-go-sdk,github.com/stainless-sdks/bem-go"

echo "==> Running tests"
go test ./... "$@"
